name: pet_track_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  go_router: ^17.2.0
  shared_preferences: ^2.5.4
  local_auth: ^2.3.0
  flutter_secure_storage: ^10.3.1
  speech_to_text: ^7.3.0
  image_picker: ^1.2.1
  dio: ^5.9.2
  get_it: ^9.2.1
  file_picker: ^8.1.7
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  equatable: ^2.0.8
  device_info_plus: ^11.5.0
  package_info_plus: ^9.0.1
  universal_html: ^2.3.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  skeletonizer: ^2.1.3
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_launcher_icons:
  image_path: "assets/logo.jpg"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo.jpg"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
  macos:
    generate: true
    image_path: "assets/logo.jpg"
  linux:
    generate: true
    image_path: "assets/logo.jpg"
