services:
  pet_track_db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1']
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - mi-red

  pet_track_backend:
    build:
      context: ./pet_track_backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./pet_track_backend/.env
    environment:
      DB_HOST: pet_track_db
      DB_PORT: 5432
    volumes:
      - media-files:/app/media
    depends_on:
      pet_track_db:
        condition: service_healthy
    networks:
      - mi-red

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - media-files:/app/media:ro
    depends_on:
      - pet_track_backend
    networks:
      - mi-red

volumes:
  postgres-prod-data:
  media-files:

networks:
  mi-red:
    driver: bridge
