# Generated by Django 5.2.17 on 2026-09-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_lostpetreport_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lostpetreport',
            table='infrastructure_lost_pet_report',
        ),
    ]
