# Generated by Django 5.2.17 on 2026-09-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreportmodel',
            name='report_type',
            field=models.CharField(choices=[('LOST', 'Perdido'), ('FOUND', 'Encontrado'), ('HOMELESS', 'Sin hogar')], default='LOST', max_length=10),
        ),
        migrations.AddField(
            model_name='lostpetreportmodel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('RESOLVED', 'Resuelto')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostpetreportmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
