# Generated by Django 5.2.17 on 2026-09-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_lostpetreportmodel_report_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_report_conversations', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='db.lostpetreportmodel')),
                ('report_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_report_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'infrastructure_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='db.conversationmodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'infrastructure_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversationmodel',
            constraint=models.UniqueConstraint(fields=('report', 'interested_user'), name='unique_report_interested_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversationmodel',
            constraint=models.CheckConstraint(condition=models.Q(('report_owner', models.F('interested_user')), _negated=True), name='conversation_participants_are_different'),
        ),
    ]
