# Generated by Django 5.2.17 on 2026-09-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_sightingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVisualFeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, default='', max_length=50)),
                ('primary_color', models.CharField(blank=True, default='', max_length=50)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=50)),
                ('markings', models.TextField(blank=True, default='')),
                ('coat_type', models.CharField(blank=True, default='', max_length=50)),
                ('ear_type', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.CharField(blank=True, default='', max_length=30)),
                ('distinctive_features', models.TextField(blank=True, default='')),
                ('analysis_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=15)),
                ('photo_hash', models.CharField(blank=True, default='', max_length=64)),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_features', to='db.lostpetreportmodel')),
            ],
            options={
                'db_table': 'infrastructure_report_visual_features',
            },
        ),
    ]
