# Generated by Django 5.2.17 on 2026-08-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostpetreport',
            options={'managed': False},
        ),
    ]
